version: "3"
services:
  qpidd:
    image: qpidd
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5671:5671"
      - "5672:5672"
    networks:
      - qpidnet
  qpiddc:
    image: qpiddc
    volumes:
       - spout-data:/opt/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - qpidnet
  qmf:
    image: qmf-git
    ports:
      - "8080:8080"
    environment:
      - QMF_GUI_ADMIN_USERNAME=admin
      - QMF_GUI_ADMIN_PASSWORD=admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - qpidnet
networks:
  qpidnet:
